@startuml View dan Export CPL-MK
actor TeamCurriculum as Foo
boundary otherPage as Foo1
boundary cpl_mk as Foo2
boundary cetak_pdf_cplmk as Foo3
control CPLMKController as Foo4
entity detail_mk_cpmk as Foo5
entity cpmk as Foo6

activate Foo
Foo -> Foo1 : url (/dashboard/kurikulum/pemetaan/cpl-mk)
activate Foo1
Foo1 -> Foo4 : index()
deactivate Foo1
activate Foo4
Foo4 -> Foo5 : Select kodeMK FROM detail_mk_cpmk
activate Foo5
Foo5 --> Foo4 : return detail_mk_cpmk
deactivate Foo5
Foo4 -> Foo6 : Select kodeCPL FROM cpmk
activate Foo6
Foo6 --> Foo4 : return list_cpmk
deactivate Foo6
Foo4 -> Foo2 : displayData()
Foo1 -> Foo : show page and data

alt Export PDF
Foo -> Foo2 : click export pdf
activate Foo2
Foo2 -> Foo4 : cetakLaporanPDF()
Foo4 -> Foo5 : Select kodeMK FROM detail_mk_cpmk
activate Foo5
Foo5 --> Foo4 : return detail_mk_cpmk
deactivate Foo5
Foo4 -> Foo6 : Select kodeCPL FROM cpmk
activate Foo6
Foo6 --> Foo4 : return list_cpmk
deactivate Foo6
Foo4 -> Foo3 : viewExcel()
activate Foo3
deactivate Foo3

else Export Excel
Foo -> Foo2 : click export pdf
Foo2 -> Foo4 : cetakLaporanExcel()
Foo2 -> Foo4 : cetakLaporanPDF()
Foo4 -> Foo5 : Select kodeMK FROM detail_mk_cpmk
activate Foo5
Foo5 --> Foo4 : return detail_mk_cpmk
deactivate Foo5
Foo4 -> Foo6 : Select kodeCPL FROM cpmk
activate Foo6
Foo6 --> Foo4 : return list_cpmk
deactivate Foo6
Foo4 --> Foo2 : retun download file

deactivate Foo
deactivate Foo2
deactivate Foo4
end

@enduml